<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>e015bc9e-db5f-41e7-ae48-9b7ca753e5a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-group [href=&quot;\?route\=Auth\/login&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-group ')]//*[@href = '?route=Auth/login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c0dda61-94ab-4697-9a71-334ea16b376c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?route=Auth/login</value>
      <webElementGuid>5facb466-8167-42bd-ba1f-a3c8e383ff81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary</value>
      <webElementGuid>def46413-0621-4ccd-8ea7-9332b9b3452d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>5257bd9d-19bb-4946-8399-b89fe20d66c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-82c9f117620b199ba6fdc8fe881330f3</value>
      <webElementGuid>a845f167-9def-4341-b3bd-64cdfd061c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-group ')]//*[@href = '?route=Auth/login']</value>
      <webElementGuid>2196a41a-27d8-40c9-91e4-7538fc58d73b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-group ')]//*[@href = '?route=Auth/login']</value>
      <webElementGuid>22d6e1a3-e38b-421c-9a4f-076f7085ccee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?route=Auth/login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>ea669782-1274-430c-85bc-a61e17b02053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
