<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>35a12658-6991-4449-a4aa-9e27a5ed445d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-group [href=&quot;\?route\=Auth\/login&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-group ')]//*[@href = '?route=Auth/login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5dc34372-41b8-4e85-ae2c-3dff29220676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?route=Auth/login</value>
      <webElementGuid>57c8fe0c-1d45-419c-a70e-99cd223bc0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary</value>
      <webElementGuid>c3ebeeb5-4c88-46a0-a66a-08c77d35b945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>077cf01f-5295-4714-add9-e942395a5a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-82c9f117620b199ba6fdc8fe881330f3</value>
      <webElementGuid>a3d21ce4-ce01-437a-aebb-1382dd710961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-group ')]//*[@href = '?route=Auth/login']</value>
      <webElementGuid>bb0e8a06-4dc2-4e17-9b06-eaec98b26fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-group ')]//*[@href = '?route=Auth/login']</value>
      <webElementGuid>7dadb2c9-2158-4520-9651-bc9c79c78b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?route=Auth/login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>82d8d933-24b7-4f40-b884-686a4f16bc49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
