<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_togglePassword</name>
   <tag></tag>
   <elementGuidId>1103b45b-3bb5-4c65-b2a7-df6ac210675b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#togglePassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'togglePassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>583553f0-1b44-4356-abec-71029aa9dcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2e057d0-18ac-4905-abf4-c16f91d29083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>togglePassword</value>
      <webElementGuid>2c98662c-c2f9-4d9a-a5e1-9d95ae56a393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle-password</value>
      <webElementGuid>6d297b32-4b42-44f4-b89e-4904c3a3b178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e9b47799dd466ee4b08b61dcb714f39c</value>
      <webElementGuid>52658770-fa06-4b11-b7c3-50f6c6e3f947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'togglePassword']</value>
      <webElementGuid>e97a814e-d212-4bdd-9245-4e69d8dc45b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'togglePassword']</value>
      <webElementGuid>d7d9f98e-8ab4-4c40-968c-bdd2556b123b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'togglePassword']</value>
      <webElementGuid>1a3b1071-3139-47cc-b531-bb9420f33515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
