<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan NIM_NIP</name>
   <tag></tag>
   <elementGuidId>7249e61a-b76d-4060-ac53-651c95dc4358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nim']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>316e7fac-4c74-497e-a00b-15057daa2b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nim</value>
      <webElementGuid>af47262f-828f-4ee6-ae46-bda675193cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e77efc1-0316-4199-8b85-2eebf60045dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>59f822fc-f67f-4c61-b397-9cf1fae46c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f2d97ee8-8fd0-4c8e-a167-b530ae7f3ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIM/NIP...</value>
      <webElementGuid>aff82472-abc2-48e9-a50c-29cf8e6d0e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>93e7960d-3652-4ec9-aee6-1847af11b60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1f01e2632059a02756dbe77d4b9c493b</value>
      <webElementGuid>1d48df8f-8019-479b-89a1-565caebd7d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nim']</value>
      <webElementGuid>4b685cea-a6ed-4e4d-b901-e9ea8831f87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nim']</value>
      <webElementGuid>da30a42a-9cc3-47d1-a7df-6e645d1994eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nim' and @type = 'text' and @name = 'username' and @placeholder = 'Masukkan NIM/NIP...']</value>
      <webElementGuid>f69b834e-51ab-4fb2-8963-1bf4897a8872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
