<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan NIM_NIP</name>
   <tag></tag>
   <elementGuidId>b632a4e7-8cb3-4b8f-93d1-cd34da5b5843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nim']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc05f5a4-a397-43a9-ba0c-bccf1f9827f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nim</value>
      <webElementGuid>65b73011-2641-4d95-8b65-6f60af4cfb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfc96f7b-c83d-4352-9439-5652f479e613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>d160f77b-8e75-497f-ba02-edd94f4f0631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0e023e6e-beae-47f7-b6f1-361dbc40b87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIM/NIP...</value>
      <webElementGuid>607dea37-5e43-4a53-8fe6-e65df240adc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f85c114-ec9b-4311-a08d-f2d5fd7c7cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1f01e2632059a02756dbe77d4b9c493b</value>
      <webElementGuid>0fbe96d8-2cff-4fc3-990d-9ff792556c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nim']</value>
      <webElementGuid>f89f2186-2472-487a-9174-6b3d69f6e28f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nim']</value>
      <webElementGuid>098c750d-8787-4b12-9050-2ed69e8947d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nim' and @type = 'text' and @name = 'username' and @placeholder = 'Masukkan NIM/NIP...']</value>
      <webElementGuid>e9e34069-731d-4249-a105-0d23ae50b0a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
