<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kembali</name>
   <tag></tag>
   <elementGuidId>396d2894-e37b-4d78-8e07-f5293de97d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a419ae5-1d93-4303-bc8e-4bc8a7209390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-add</value>
      <webElementGuid>89596ebb-6bc7-44d6-9033-0bebf9552709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?route=Admin/dataRuangan</value>
      <webElementGuid>d34dcf95-0adc-4a8e-b865-847e4919008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>a7c5caa8-cdf7-4132-a573-1c7c145755f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8f9571fe0ec66210772d441e27aa1492</value>
      <webElementGuid>c230c1f4-c197-4079-ad5a-c44bc6d09dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      <webElementGuid>3e2f88ff-0aad-473b-829c-d73a0242109f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      <webElementGuid>75b585de-0cb9-4147-8c70-86b34d0a75b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?route=Admin/dataRuangan' and (text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>90e44b36-46cf-4868-959c-702ec6b2611d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
