<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ubah_1</name>
   <tag></tag>
   <elementGuidId>9b429957-1538-4ced-9e00-d700c601aef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.room-card:nth-child(3) .btn-edit:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' room-card ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-edit ') and (position() = 3)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88f3fc5a-6e58-4102-aad3-fd22ac55667e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action btn-edit</value>
      <webElementGuid>2ff80003-3192-45e4-8291-8ba8989f03d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?route=Admin/editRuangan/21</value>
      <webElementGuid>e673e184-6c08-46de-baf4-00b13f09c923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>1ddfc585-f27a-4db8-86f2-8b04a728f8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ecb21b14baf78b1669ccf442d76beb61</value>
      <webElementGuid>9bdb0eb9-d7cc-48f7-82ff-6fbeaf08abde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' room-card ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-edit ') and (position() = 3)]</value>
      <webElementGuid>5e7845a4-8657-456b-baaa-2480a98ff526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' room-card ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-edit ') and (position() = 3)]</value>
      <webElementGuid>96cf8edb-9915-47e0-8f8a-dde38f159832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?route=Admin/editRuangan/21' and (text() = 'Ubah' or . = 'Ubah')]</value>
      <webElementGuid>80beaa6a-1eb2-4221-ae4b-2a0695547b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
