<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus</name>
   <tag></tag>
   <elementGuidId>1e9dfa65-813d-4bea-a475-c699c11214fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-name=&quot;Ruangan\ Ceria&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-name = 'Ruangan Ceria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f73aff4a-baa3-4450-aef6-35a0a4c6e6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c434106e-fdb6-460e-bcde-08e3ac7f5559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action btn-delete js-open-delete</value>
      <webElementGuid>5ea24fbc-776f-444e-9e86-19cd43cd662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>9cb17427-8de1-4dd5-a983-49b493ee67b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Ruangan Ceria</value>
      <webElementGuid>acff4864-4ced-47d1-af36-4f75be23a37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Hapus
                  </value>
      <webElementGuid>edca3692-c78c-4e2a-9bec-17796a41e5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2cd0b8d3698d6b8222e9c68f26d01d8d</value>
      <webElementGuid>7c6a1875-7b37-4714-ae23-8b3bc3db49c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-name = 'Ruangan Ceria']</value>
      <webElementGuid>6befb531-cb58-4876-94b7-9d658653e963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-name = 'Ruangan Ceria']</value>
      <webElementGuid>dae08618-a164-49df-8bf0-504d06fbd8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                    Hapus
                  ' or . = '
                    Hapus
                  ')]</value>
      <webElementGuid>b64f3ce9-5f46-43e1-a869-8e9f22075262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
