<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya, hapus</name>
   <tag></tag>
   <elementGuidId>84eccbc6-7489-4368-a565-a6fc59b4c2bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-modal-red</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-modal-red ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c689d31-b9b4-45bf-bc4f-8558ec9f8d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7669f21b-d3c1-4b25-9802-8591e3be3740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-modal-red</value>
      <webElementGuid>4b1984d2-06cc-4109-9d98-e9e703968172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya, hapus</value>
      <webElementGuid>8ed3cc0f-b683-486e-bf32-102a5fa9b544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e06091a1d695e2fefda0fed6c05bd7c</value>
      <webElementGuid>597cebc7-a1e1-4576-8afb-2b563f970616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-modal-red ')]</value>
      <webElementGuid>f303b059-36c3-409b-8582-45858383db1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-modal-red ')]</value>
      <webElementGuid>83aed0f3-e37d-4ff4-bb26-36020fab4f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Ya, hapus' or . = 'Ya, hapus')]</value>
      <webElementGuid>226c0021-f090-4324-b696-0293e2a11ba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
