<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus</name>
   <tag></tag>
   <elementGuidId>93870ee7-08e1-4b7d-8ab3-6eb1b0db8acc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-name=&quot;Ruang\ Ceria&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-name = 'Ruang Ceria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b3bcffd-ccc8-4dd1-9373-394a82f5cf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70757109-6e16-4340-9860-d6ddaca11e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action btn-delete js-open-delete</value>
      <webElementGuid>0bc37c55-c14e-4c76-9c0d-4596ec8158a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>e4d46be1-5a3a-4c9d-9ba7-f0535c8e3130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Ruang Ceria</value>
      <webElementGuid>319d140b-d5fb-48fd-9972-fdb0d7d3bab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Hapus
                  </value>
      <webElementGuid>6db0ca2e-9b18-4c44-86a1-73d6f71556d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5370cf51f881593ee2ab0ec37765c052</value>
      <webElementGuid>3754332b-a78a-4fac-8890-089ae47fb45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-name = 'Ruang Ceria']</value>
      <webElementGuid>4eec12ee-79f1-4579-b03a-0df7298b1a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-name = 'Ruang Ceria']</value>
      <webElementGuid>40a07e43-44a1-4431-8c6b-a49dd216c1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                    Hapus
                  ' or . = '
                    Hapus
                  ')]</value>
      <webElementGuid>6c8a7d39-a7dc-47be-b768-5fe7665d859d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
