<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Ruangan</name>
   <tag></tag>
   <elementGuidId>0692fe03-702e-4a23-a212-757efe21aa4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bec2ab5a-f4a3-4bcc-893a-10ac1159854a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-add</value>
      <webElementGuid>f0f35fbc-3d9e-47ab-b86a-ad8cfbdcc2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b39b991f-ae1e-4800-988c-64605eed2b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location='?route=Admin/addRuangan'</value>
      <webElementGuid>c2974453-3988-49eb-974f-0c85521beed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Ruangan</value>
      <webElementGuid>071118f7-b1cc-4cba-bc7f-fa5a5befa8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8f9571fe0ec66210772d441e27aa1492</value>
      <webElementGuid>210b7597-86a3-4f83-a913-8e7cc89124ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      <webElementGuid>91081d59-4081-464d-a9f0-52ce71bfa4fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      <webElementGuid>ca60dbc7-0836-409d-80d3-0112f1f56c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tambah Ruangan' or . = 'Tambah Ruangan')]</value>
      <webElementGuid>881f9046-07da-41a2-bb54-bf4f78f8397b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
