<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Ruangan</name>
   <tag></tag>
   <elementGuidId>4f1efafd-e950-4eba-b4b8-9f425f6e012f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>233079b3-b1ad-40aa-b10b-8c96e592bed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-add</value>
      <webElementGuid>fcdd171f-bc18-4249-9926-6723a6bf5a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4678af8c-f6ae-44f3-8dae-0ea0e9a6cd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location='?route=Admin/addRuangan'</value>
      <webElementGuid>f8f822e8-e602-45f3-b78e-8dd4c744f30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Ruangan</value>
      <webElementGuid>88dbd70d-820f-4c7c-bccc-d7e1e9a3d4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8f9571fe0ec66210772d441e27aa1492</value>
      <webElementGuid>5dc819ea-a171-4166-9ba5-5ac0c408e2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      <webElementGuid>01dd395b-668f-48cc-8b66-347d5ddd383d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-add ')]</value>
      <webElementGuid>c38d782c-a8c4-42ac-8f2a-cda4593e5572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tambah Ruangan' or . = 'Tambah Ruangan')]</value>
      <webElementGuid>8daea7ac-fbff-4413-857f-13f260ebe842</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
